name: On push to develop

on:
  push:
    branches:
      - develop

jobs:
  publish:
    name: Publish
    uses: ./.github/workflows/publish.yml
    with:
      tag: next
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
