name: On push to rc/*

on:
  push:
    branches:
      - rc/*

jobs:
  dependencies:
    name: Install dependencies
    uses: ./.github/workflows/install_dependencies.yml

  qa:
    name: Quality assurance
    needs: dependencies
    uses: ./.github/workflows/qa.yml

  test:
    name: Test
    needs: qa
    uses: ./.github/workflows/test.yml

  tag:
    name: Tag
    needs: test
    uses: ./.github/workflows/tag.yml
    secrets:
      PERSONAL_ACCESS_TOKEN_FOR_PUSH_TAG: ${{ secrets.PERSONAL_ACCESS_TOKEN_FOR_PUSH_TAG }}
