name: On push to develop

on:
  push:
    branches:
      - develop

jobs:
  dependencies:
    name: Install dependencies
    uses: ./.github/workflows/install_dependencies.yml

  qa:
    name: Quality assurance
    needs: dependencies
    uses: ./.github/workflows/qa.yml

  test:
    name: Test
    needs: qa
    uses: ./.github/workflows/test.yml

  publish:
    name: Publish
    uses: ./.github/workflows/publish.yml
    with:
      version: next
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
