name: On tag release candidate

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-rc.+'

jobs:
  semver:
    name: Version parser
    runs-on: ubuntu-22.04
    outputs:
      version: ${{ steps.parser.outputs.version }}
    steps:
      - name: Parse version
        id: parser
        run: |
          version_tag=${{ github.ref_name }}
          echo "version_tag: $version_tag"
          # First, try to remove the "refs/tags/" prefix, after that remove the "v" prefix
          version=$(echo "$version_tag" | sed -E 's|^refs/tags/||; s|^v||')
          echo "version: $version"
          echo "version=$version" >> $GITHUB_OUTPUT

  release:
    name: Release
    needs: semver
    uses: ./.github/workflows/release.yml
    with:
      version: ${{ needs.semver.outputs.version }}
      prerelease: true
