name: Publish library

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
    secrets:
      NPM_TOKEN:
        required: true

jobs:
  dependencies:
    name: Install dependencies
    uses: ./.github/workflows/install_dependencies.yml

  qa:
    name: Quality assurance
    needs: dependencies
    uses: ./.github/workflows/qa.yml

  test:
    name: Test
    needs: qa
    uses: ./.github/workflows/test.yml

  publish_to_npm:
    name: Publish to NPM
    needs: test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: "v${{ inputs.version }}"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Starting cache for dependencies
        id: npm_install
        uses: actions/cache@v3
        with:
            path: 'node_modules'
            key: ${{ runner.os }}-modules-${{ hashFiles('package-lock.json') }}
      
      - name: Build library
        run: npm run build

      - name: Publish
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          strategy: all
          tag: ${{ inputs.version }}