name: Publish library

on:
  workflow_call:

jobs:
  semver:
    name: Version parser
    runs-on: ubuntu-22.04
    outputs:
      version: ${{ steps.parser.outputs.version }}
    steps:
      - name: Parse version
        id: parser
        run: |
          version_tag=${{ env.VERSION_REF }}
          echo "version_tag: $version_tag"
          version=$(echo "$version_tag" | sed 's/refs\/tags\/v//')
          echo "version: $version"
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.version }}

      - name: Publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}