name: Create release

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
    prerelease:
      type: boolean
      default: false

jobs:
  job:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.version }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ inputs.version }}
          release_name: Release ${{ inputs.version }} }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: true
          prerelease: ${{ inputs.prerelease }}

