name: Create Tag

on:
  workflow_call:
    secrets:
      PERSONAL_ACCESS_TOKEN_FOR_PUSH_TAG:
        required: true


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: butlerlogic/action-autotag@1.1.2
      env:
        GITHUB_TOKEN: "${{ secrets.PERSONAL_ACCESS_TOKEN_FOR_PUSH_TAG }}"
      with:
        tag_prefix: "v"